# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43b07f21b2b95381409b105ae39a4f1bd8975ce6db45a4e5970ab59a633398f38485419bcc703d0b89625ee2367989a4967ee77aacdf55beb993b0a194d4bedc

test:
  secret_key_base: 92e95772c26b17f66d4e607e0e76a7faa9b200b267d8d36482bc98d9a0001f5ddc20bc6c29ca51dfdb8860309cd698a3304aa140ec17228fbf23a87a5ee48a2b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
